# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SaveEarth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SaveEarth
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKLink'    # 메시지(카카오링크)

end


